# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
          time: "03:33"
      open-pull-requests-limit: 25

    - package-ecosystem: "gomod"
      directory: "/"
      schedule:
          interval: "daily"
          time: "03:33"
      open-pull-requests-limit: 25

    - package-ecosystem: "elm"
      directory: "/"
      schedule:
          interval: "daily"
          time: "03:33"
      open-pull-requests-limit: 25

    - package-ecosystem: "elm"
      directory: "/review/"
      schedule:
          interval: "daily"
          time: "03:33"
      open-pull-requests-limit: 25

    - package-ecosystem: "docker"
      directory: "/docker/"
      schedule:
          interval: "daily"
          time: "03:33"
      open-pull-requests-limit: 25

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
          time: "03:33"
      open-pull-requests-limit: 25

    - package-ecosystem: "devcontainers"
      directory: "/"
      schedule:
          interval: "daily"
          time: "03:33"
