schema {
    query: RootQuery
    mutation: RootMutation
    subscription: RootSubscription
}

type RootQuery {
    workClock: WorkClockQuery!
}

type RootMutation {
    workClock: WorkClockMutation!
}

type RootSubscription {
    workClock: WorkClockQuery!
    general: GeneralQuery!
}
