type HistoryItem {
	"""
	The timestamp when the activity started.
	"""
	start: Timestamp!

	"""
	The timestamp when the activity ended.
	If the activity is still ongoing, this field is null.
	"""
	end: Timestamp
}

type HistoryQuery {
	"""
	Returns the history of the user's activity.

	`limit` can be used to limit the number of history items returned.
	If `limit` is not provided, no limit will be applied.

	When neither `from` nor `to` is provided, the fist entry will be the newest one.
	All entries will be sorted by the `start` timestamp in descending order.

	When only `from` is provided, entries with the same, a later or no `end` timestamp will be returned.
	This time they are sorted by the `start` timestamp in ascending order.

	When only `to` is provided, entries with the same or an earlier start timestamp will be returned.
	This time they are sorted by the `start` timestamp in descending order.

	When both `from` and `to` are provided, entries which overlap the range will be returned.
	This time they are sorted by the `start` timestamp in ascending order.
	"""
	historyItems(from: Timestamp, to: Timestamp, limit: Int): [HistoryItem!]!
}
