name: Build ResMon

on:
    push:
        branches: []

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.22"

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"

            - name: Create empty file in webroot
              run: mkdir -p webroot && touch webroot/empty

            - name: Install go dependencies
              run: go install

            - name: Install npm dependencies
              run: npm ci

            - name: Run generate
              run: npm run generate

            - name: Run tests
              run: npm run test

            - name: Build documentation
              run: npm run build:docs

            - name: Build project
              run: npm run build

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Cache Docker layers
              uses: actions/cache@v4
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            - name: Prepare docker tags
              id: prepare_docker_tags
              run: |
                BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/[^a-zA-Z0-9]/-/g')
                SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
                echo "::set-output name=branch_tag::yertools/res-mon:$BRANCH_NAME"
                echo "::set-output name=commit_tag::yertools/res-mon:$BRANCH_NAME-$SHORT_SHA"
                if [[ "$BRANCH_NAME" == "main" ]]; then
                  echo "::set-output name=latest_tag::yertools/res-mon:latest"
                fi

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./docker/Release.Dockerfile
                  push: true
                  tags: |
                    ${{ steps.prepare_docker_tags.outputs.commit_tag }}
                    ${{ steps.prepare_docker_tags.outputs.branch_tag }}
                    ${{ steps.prepare_docker_tags.outputs.latest_tag }}
                  labels: yertools/res-mon
                  builder: ${{ steps.buildx.outputs.name }}
                  platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache
