name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.1.0"
          rebar3-version: "3"
      - run: cd res_mon && gleam deps download
      - run: cd res_mon && gleam test
      - run: cd res_mon && gleam format --check src test
      - run: cd res_mon_frontend && gleam deps download
      - run: cd res_mon_frontend && gleam test
      - run: cd res_mon_frontend && gleam format --check src test
    